enum trovo_scope {
    USER_DETAILS_SELF,

    CHANNEL_DETAILS_SELF,
    // CHANNEL_UPDATE_SELF,
    // CHANNEL_SUBSCRIPTIONS,

    CHAT_CONNECT,
    CHAT_SEND_SELF,
    SEND_TO_MY_CHANNEL,
    MANAGE_MESSAGES;

}
